server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "instagram-clone-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: USERNAME
    password: PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
app:
  email:
    from: EMAIL